import {
  LayoutDashboard,
  Package,
  Boxes,
  Truck,
  Factory,
  ShoppingCart,
  BrainCircuit,
  ClipboardList,
  AlertTriangle,
  CheckCircle2,
  FileText,
  Users,
} from "lucide-react";

export const MENU_ITEMS = Object.freeze([
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    path: "/dashboard",
    roles: ["ADMIN", "MANAGER", "ANALYST", "OPERATOR"],
  },
  {
    id: "products",
    title: "Products",
    icon: Package,
    path: "/products",
    roles: ["ADMIN", "MANAGER"],
  },
  {
    id: "inventory",
    title: "Inventory",
    icon: Boxes,
    path: "/inventory",
    roles: ["ADMIN", "MANAGER", "OPERATOR"],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    icon: Truck,
    path: "/suppliers",
    roles: ["ADMIN", "MANAGER"],
  },
  {
    id: "production",
    title: "Production",
    icon: Factory,
    path: "/production",
    roles: ["ADMIN", "MANAGER"],
  },
  {
    id: "orders",
    title: "Orders",
    icon: ShoppingCart,
    path: "/orders",
    roles: ["ADMIN", "MANAGER", "OPERATOR"],
  },
  {
    id: "forecast",
    title: "Forecast",
    icon: BrainCircuit,
    path: "/forecast",
    roles: ["ADMIN", "MANAGER", "ANALYST"],
  },
  {
    id: "tasks",
    title: "Tasks",
    icon: ClipboardList,
    path: "/tasks",
    roles: ["ADMIN", "MANAGER", "OPERATOR"],
  },
  {
    id: "complaints",
    title: "Complaints",
    icon: AlertTriangle,
    path: "/complaints",
    roles: ["ADMIN", "MANAGER", "OPERATOR"],
  },
  {
    id: "approvals",
    title: "Approvals",
    icon: CheckCircle2,
    path: "/approvals",
    roles: ["ADMIN", "MANAGER"],
  },
  {
    id: "reports",
    title: "Reports",
    icon: FileText,
    path: "/reports",
    roles: ["ADMIN", "MANAGER", "ANALYST"],
  },
  {
    id: "users",
    title: "Users",
    icon: Users,
    path: "/users",
    roles: ["ADMIN"],
  },
]);
